require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UserTokensController do

  # This should return the minimal set of attributes required to create a valid
  # UserToken. As you add validations to UserToken, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "provider" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UserTokensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all user_tokens as @user_tokens" do
      user_token = UserToken.create! valid_attributes
      get :index, {}, valid_session
      assigns(:user_tokens).should eq([user_token])
    end
  end

  describe "GET show" do
    it "assigns the requested user_token as @user_token" do
      user_token = UserToken.create! valid_attributes
      get :show, {:id => user_token.to_param}, valid_session
      assigns(:user_token).should eq(user_token)
    end
  end

  describe "GET new" do
    it "assigns a new user_token as @user_token" do
      get :new, {}, valid_session
      assigns(:user_token).should be_a_new(UserToken)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_token as @user_token" do
      user_token = UserToken.create! valid_attributes
      get :edit, {:id => user_token.to_param}, valid_session
      assigns(:user_token).should eq(user_token)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new UserToken" do
        expect {
          post :create, {:user_token => valid_attributes}, valid_session
        }.to change(UserToken, :count).by(1)
      end

      it "assigns a newly created user_token as @user_token" do
        post :create, {:user_token => valid_attributes}, valid_session
        assigns(:user_token).should be_a(UserToken)
        assigns(:user_token).should be_persisted
      end

      it "redirects to the created user_token" do
        post :create, {:user_token => valid_attributes}, valid_session
        response.should redirect_to(UserToken.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_token as @user_token" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserToken.any_instance.stub(:save).and_return(false)
        post :create, {:user_token => { "provider" => "invalid value" }}, valid_session
        assigns(:user_token).should be_a_new(UserToken)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        UserToken.any_instance.stub(:save).and_return(false)
        post :create, {:user_token => { "provider" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_token" do
        user_token = UserToken.create! valid_attributes
        # Assuming there are no other user_tokens in the database, this
        # specifies that the UserToken created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        UserToken.any_instance.should_receive(:update).with({ "provider" => "MyString" })
        put :update, {:id => user_token.to_param, :user_token => { "provider" => "MyString" }}, valid_session
      end

      it "assigns the requested user_token as @user_token" do
        user_token = UserToken.create! valid_attributes
        put :update, {:id => user_token.to_param, :user_token => valid_attributes}, valid_session
        assigns(:user_token).should eq(user_token)
      end

      it "redirects to the user_token" do
        user_token = UserToken.create! valid_attributes
        put :update, {:id => user_token.to_param, :user_token => valid_attributes}, valid_session
        response.should redirect_to(user_token)
      end
    end

    describe "with invalid params" do
      it "assigns the user_token as @user_token" do
        user_token = UserToken.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserToken.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_token.to_param, :user_token => { "provider" => "invalid value" }}, valid_session
        assigns(:user_token).should eq(user_token)
      end

      it "re-renders the 'edit' template" do
        user_token = UserToken.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        UserToken.any_instance.stub(:save).and_return(false)
        put :update, {:id => user_token.to_param, :user_token => { "provider" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_token" do
      user_token = UserToken.create! valid_attributes
      expect {
        delete :destroy, {:id => user_token.to_param}, valid_session
      }.to change(UserToken, :count).by(-1)
    end

    it "redirects to the user_tokens list" do
      user_token = UserToken.create! valid_attributes
      delete :destroy, {:id => user_token.to_param}, valid_session
      response.should redirect_to(user_tokens_url)
    end
  end

end
